<a href="https://colab.research.google.com/github/vinayvpanicker/Vinay-V-Panicker/blob/master/Python_MLPackages.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy

In [1]:
import numpy as np

In [2]:
a = np.array([0,1,2])
print([0,1,2], type([0,1,2]))
print ('Array a has value = {} and type = {}, shape = {}'.format(a, type(a), a.shape))

[0, 1, 2] <class 'list'>
Array a has value = [0 1 2] and type = <class 'numpy.ndarray'>, shape = (3,)


In [3]:
b = np.array([[0,1,2], [3,4,5]])
print ('Array b has value = \n{}\n and type = {}'.format(b, type(b)))
print(b.shape)
print(b[0,0], b[0,1], b[0,2])
print(b[1,0], b[1,1], b[1,2])
print(type(b[:,1]))

Array b has value = 
[[0 1 2]
 [3 4 5]]
 and type = <class 'numpy.ndarray'>
(2, 3)
0 1 2
3 4 5
<class 'numpy.ndarray'>


In [4]:
a = np.ones((3,4))
print(a)
print(a[0,0])

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
1.0


In [5]:
e = np.eye(5, dtype=int )
print(e, e.shape)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]] (5, 5)


In [6]:
h = np.array(([0, 1, 2.0], [1 + 2j, 5, 0.2], (0, 1, 0)))
print(h)
print(type(h))

[[0. +0.j 1. +0.j 2. +0.j]
 [1. +2.j 5. +0.j 0.2+0.j]
 [0. +0.j 1. +0.j 0. +0.j]]
<class 'numpy.ndarray'>


In [7]:
j = np.linspace(2.0, 4.0, 12)
print(j)
print(j.shape)

[2.         2.18181818 2.36363636 2.54545455 2.72727273 2.90909091
 3.09090909 3.27272727 3.45454545 3.63636364 3.81818182 4.        ]
(12,)


In [8]:
jj = j.reshape(3,4)
print(jj)
print(jj.shape)

[[2.         2.18181818 2.36363636 2.54545455]
 [2.72727273 2.90909091 3.09090909 3.27272727]
 [3.45454545 3.63636364 3.81818182 4.        ]]
(3, 4)


In [9]:
k = np.indices((4,3))
print(k)
print(k.shape)

[[[0 0 0]
  [1 1 1]
  [2 2 2]
  [3 3 3]]

 [[0 1 2]
  [0 1 2]
  [0 1 2]
  [0 1 2]]]
(2, 4, 3)


In [10]:
x = np.arange(4,20, 2)
print(x)

[ 4  6  8 10 12 14 16 18]


In [11]:
x = np.arange(20).reshape(5, 4)
print(x)
row, col = np.indices((2, 3))
print(x[row, col])


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[0 1 2]
 [4 5 6]]


In [12]:
y = np.array([[[1],[2],[3]], [[4],[5],[6]]])
print('y = {}\n Shape of y = {}\n y[1:3] = {}\n y[1:3].shape = {}'.format(y, 
                                                                          y.shape, 
                                                                          y[1:3], 
                                                                          y[1:3].shape))

y = [[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]
 Shape of y = (2, 3, 1)
 y[1:3] = [[[4]
  [5]
  [6]]]
 y[1:3].shape = (1, 3, 1)


In [13]:
a = np.array([[1,2,4], [3,6,9], [5,10,15]])
print(np.array([a[0,0], a[1,1], a[2,1]]))
print(a[[0,1,2],[0,1,1]], a[[0,1,2],[0,1,1]].shape)

[ 1  6 10]
[ 1  6 10] (3,)


In [14]:
print(a)
print(a == 5)

[[ 1  2  4]
 [ 3  6  9]
 [ 5 10 15]]
[[False False False]
 [False False False]
 [ True False False]]


In [15]:
print(a[a>5])
b = np.array([[1,4,16], [3, 12, 52], [21, 9, 10]])
print(a[a%3 == 0], '\n', b[a%3 == 0])

[ 6  9 10 15]
[ 3  6  9 15] 
 [ 3 12 52 10]


In [ ]:
x = np.array([[1,2], [3,4]])
y = np.array([[3,6], [4,8]])
a = np.array([2,8])
b = np.array([3,27])
print(x.dot(y))
print(np.dot(a,b))
print(np.dot(x,y))

In [18]:
a = np.array([2,8])
print(x, y, a, sep='\n', end='\n\n')
print(a+x)
#print(x*5)
#print(x+y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]
[2 8]



ValueError: ignored

In [16]:
a = np.array([[1,1,1], [2,4,6], [3,6,9]])
v = np.array([1, 0, 1]).reshape(3,1)
b = np.empty_like(a)
print(a)
#for i in range(3):
#    b[i, :] = a[i, :] + v
#print (b)
print(a+v)
print(v.shape)

[[1 1 1]
 [2 4 6]
 [3 6 9]]
[[ 2  2  2]
 [ 2  4  6]
 [ 4  7 10]]
(3, 1)


In [17]:
v = np.array([1,2,3,2])
w = np.array([4,5])
#print(v*w) # Does not work due to size mismatch
print(np.reshape(v, (4,1)) * w)

print(v.shape)
v = v.reshape(2,2)
print(v, v.shape)

[[ 4  5]
 [ 8 10]
 [12 15]
 [ 8 10]]
(4,)
[[1 2]
 [3 2]] (2, 2)


In [ ]:
arr = np.array([[101,222], [32,34], [5,6]], dtype=np.float32)
np.savetxt('myarr.txt', arr, delimiter=';')

In [ ]:
with open('myarr.txt', 'r') as f:
    print(f.read())

In [ ]:
r_arr = np.genfromtxt('myarr.txt', delimiter=';', skip_header=0)
print(r_arr)

#SciPy

In [ ]:
from scipy import stats
dir(stats)

In [ ]:
help(dir)

In [ ]:
import scipy as sp
v = sp.randn(5)
print(v, type(v))

In [ ]:
print("Mean = {}\nMin = {}\nVariance = {}\nStDev = {}".format(v.mean(),
                                                              v.min(), 
                                                              v.var(), 
                                                              v.std()))

In [ ]:
from scipy import stats
stats.describe(v)

In [ ]:
n,minmax,mean,var,skew,kurt = stats.describe(v)
print(minmax)
print(mean)
print(var)
print(skew)
print(kurt)

In [ ]:
from scipy.stats import norm
print (norm.ppf(0.5, loc=123.4))
#help(norm.ppf)
print(norm.ppf(0.95, loc=172.7815, scale=4.1532))


In [ ]:
a = np.array([[3, 2, 0], [1, -1, 0], [0, 5, 1]])
b = np.array([2, 4, -1])
from scipy import linalg
x = linalg.solve(a, b)
x

In [ ]:
a = np.array([[3, 2, 0], [3, 3, 0], [0, 5, 1]])
b = np.array([2, 2, -1])
from scipy import linalg
x = linalg.solve(a, b)
x

In [ ]:
a = np.array([[3, 2, 0], [6, 4, 0], [0, 5, 1]])
b = np.array([2, 4, -1])
from scipy import linalg
x = linalg.solve(a, b)
x

In [ ]:
from scipy import misc
import imageio
import matplotlib.pyplot as plt
f = misc.face()
imageio.imwrite('image.png', f)
plt.imshow(f)
plt.show()

In [ ]:
from matplotlib import pyplot
from pandas import read_csv
from pandas.plotting import scatter_matrix
filename = "indians-diabetes.data"
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
data = read_csv(filename, names=names)
scatter_matrix(data)
pyplot.show()


# Pandas

In [ ]:
import pandas as pd

In [ ]:
s = pd.Series([9,8,7,5], dtype=int)
print(s)

In [ ]:
s2 = pd.Series(list('9876'))
print(s2)
print(s2[[0,3]])

In [ ]:
s = pd.Series([9,8,7,6], index=['#','$','%','^'])
print(s)
print(s[['^','$']])

In [ ]:
s = pd.Series(tuple('abcdef'))
s

In [ ]:
s = pd.Series([1,2,3,4,5], index=list("xyxxz"))
s

In [ ]:
s['x']

In [ ]:
s['w'] = 52
s

In [ ]:
s1 = pd.Series({1:1, 2:4, 4:16}, index=[1,2,3,4])
s1

In [ ]:
s1[[2,3]]

In [ ]:
s1*5

In [ ]:
s1*s1

In [ ]:
s1>5

In [ ]:
data = {'country':['INDIA', 'USA', 'INDIA', 'USA'],
        'Year':[2010,2011,2012,2013],
        'Population':[20,28,32,38]}
df = pd.DataFrame(data)
df

In [ ]:
df['GDP'] = [6.3, 5.7, 7.8, 5.5]
df

In [ ]:
df['GDP'].sum()

In [ ]:
df.Population.mean()

In [ ]:
df.describe()

In [ ]:
s1.describe()

In [ ]:
data = pd.read_csv('sample_data/california_housing_train.csv')
data.describe()

In [ ]:
data

In [ ]:
len(data)

In [ ]:
data.columns

In [ ]:
data.head(10)

In [ ]:
data['longitude']

In [ ]:
data.longitude.head(5)

In [ ]:
s1

In [ ]:
s1.dropna()

In [ ]:
s1

In [ ]:
s2 = s1 > 4
s2

In [ ]:
s2.duplicated()

In [ ]:
s10 = pd.Series([0,1,1,2,2,3,4,5,5,6])
s10

In [ ]:
s10.duplicated()

In [ ]:
s10.drop_duplicates()

In [ ]:
print(s1)
s3 = s1.fillna(112233)
s3

In [ ]:
pd.isnull(s1)

In [ ]:
pd.isnull(s3)

In [ ]:
print('S1 = ', s1)
print('S2 = ', s2)

In [ ]:
s4 = pd.concat([s1,s2])
s4

In [ ]:
s5 = pd.concat([s1,s2], axis=1)
print(type(s1), type(s5))
s5

# Matplotlib

In [ ]:
import matplotlib.pyplot as plt
import numpy as np


In [ ]:
a = np.array(range(11))
plt.plot(a)
plt.xlabel('MyX')
plt.ylabel('MyY')
plt.show()

In [ ]:
x = np.array(range(10))
y = np.array(range(0,20,2))
plt.plot(x,y)

In [ ]:
u, a = 0, 0
def dist(t):
    return u*t + 0.5*a*t*t

u, a = 5, 25
T = np.arange(-5.0, 5.1, 0.1)
plt.plot(T, dist(T))
plt.xlabel('time')
plt.ylabel('distance')
plt.show()

In [ ]:
# Univariate Histograms
from matplotlib import pyplot
from pandas import read_csv
filename = 'sample_data/pima-indians-diabetes.csv'
mynames = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
data = read_csv(filename, names=mynames)
data.hist()
pyplot.show()


In [ ]:
# Univariate Density Plots
from matplotlib import pyplot
from pandas import read_csv
filename = 'sample_data/pima-indians-diabetes.csv'
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
data = read_csv(filename, names=names)
data.plot(kind='density', subplots=True, layout=(3,3), sharex=False)
pyplot.show()


In [ ]:
from matplotlib import pyplot
from pandas import read_csv
filename = 'sample_data/pima-indians-diabetes.csv'
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
data = read_csv(filename, names=names)
data.plot(kind='box', subplots=True, layout=(3,3), sharex=False, sharey=False)
pyplot.show()


In [ ]:
from matplotlib import pyplot
from pandas import read_csv
import numpy
filename = 'sample_data/pima-indians-diabetes.csv'
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
data = read_csv(filename, names=names)
correlations = data.corr()
# plot correlation matrix
fig = pyplot.figure()
ax = fig.add_subplot(111)
cax = ax.matshow(correlations, vmin=-1, vmax=1)
fig.colorbar(cax)
ticks = numpy.arange(0,9,1)
ax.set_xticks(ticks)
ax.set_yticks(ticks)
ax.set_xticklabels(names)
ax.set_yticklabels(names)
pyplot.show()


In [ ]:
from matplotlib import pyplot
from pandas import read_csv
from pandas.plotting import scatter_matrix
filename = 'sample_data/pima-indians-diabetes.csv'
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
data = read_csv(filename, names=names)
scatter_matrix(data)
pyplot.show()
